In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
import seaborn as sns

In [3]:
df = pd.read_csv('Titanic.csv')[['Age','Pclass','SibSp','Parch','Survived']]
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [4]:
df.dropna(inplace = True)
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [5]:
x = df.iloc[:,0:4]
y = df.iloc[:,-1]
x.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [6]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

In [7]:
# Applying Feature Construction:

In [8]:
x['Family_size'] = x.SibSp + x.Parch +1
x.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [9]:
def myfunc(num):
    if num ==1:      #alone
        return 0
    elif num > 1 and num <= 4:   #small famly
        return 1
    else:               #large family
        return 2

myfunc(4)

1

In [11]:
x['Family_Type'] = x.Family_size.apply(myfunc)
x.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_Type
0  22.0       3      1      0            1            0
1  38.0       1      1      0            1            0
2  26.0       3      0      0            0            2
3  35.0       1      1      0            1            0
4  35.0       3      0      0            0            2

In [12]:
x.drop(columns=['SibSp','Parch','Family_size'], inplace=True)
x.head()

    Age  Pclass  Family_Type
0  22.0       3            0
1  38.0       1            0
2  26.0       3            2
3  35.0       1            0
4  35.0       3            2

In [13]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

# it increased from 63% to 73%:

np.float64(0.7312698412698414)

In [14]:
# Feature Splitting:

In [15]:
df = pd.read_csv('Titanic.csv')
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [16]:
# here the name have title like mr,mrs which can also reduce the accuracy:
df.Name

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [20]:
df['Title'] = df.Name.str.split(', ', expand = True)[0]
df.Title

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: Title, Length: 891, dtype: object

In [21]:
df['Title'] = df.Name.str.split(', ', expand = True)[1]
df.Title

0                                 Mr. Owen Harris
1      Mrs. John Bradley (Florence Briggs Thayer)
2                                     Miss. Laina
3              Mrs. Jacques Heath (Lily May Peel)
4                               Mr. William Henry
                          ...
886                                   Rev. Juozas
887                          Miss. Margaret Edith
888                Miss. Catherine Helen "Carrie"
889                               Mr. Karl Howell
890                                   Mr. Patrick
Name: Title, Length: 891, dtype: object

In [23]:
df['Title'] = df.Name.str.split(', ', expand = True)[1].str.split('.', expand=True)[0]
df[['Title','Name']]

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [24]:
# we can create married and unmaried now with mr, miss, mrs title:

In [26]:
(df.groupby('Title')['Survived']).mean().sort_values(ascending=False)
# we can also see Mrs, Miss ,etc have high survival rate:

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [28]:
df['Is_married'] = 0
df.loc[df.Title == 'Mrs', 'Is_married'] = 1

In [29]:
df.Is_married

0      0
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_married, Length: 891, dtype: int64